
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf.template /etc/nginx/conf.d/default.conf

ENV PORT=8080
ENV BACKEND_URL=http://java-backend:8080

EXPOSE 8080

CMD sh -c "sed -i \"s|PLACEHOLDER_BACKEND_URL|$BACKEND_URL|g\" /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
