
FROM postgres:16.4

RUN set -xe; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
    postgresql-16-pgvector \
    postgresql-16-age; \
    rm -rf /var/lib/apt/lists/*

RUN echo "shared_preload_libraries = 'age'" >> /usr/share/postgresql/postgresql.conf.sample

EXPOSE 5432