app.base-url=${APP_BASE_URL:http://localhost:8080}

spring.application.name=univflow

server.port=${PORT:8080}
logging.level.root=INFO
logging.level.com.disertatie.univflow=DEBUG
server.servlet.context-path=/api

security.jwt.secret-key=${JWT_SECRET_KEY:guef0dacbuNjmgB38CBGdv18Rr5Z9znIY2c8i92D1YJU6qf2hvkuywu5e5ALm4mVWfL59bbVQjEeZFmXVu7Bug==}
security.jwt.expiration-time=3600000
security.jwt.refresh-token.expiration=86400000


python.service.base-url=${PYTHON_BASE_URL:http://localhost:8000}
python.service.ingest-url=${INGEST_SERVICE_URL:http://localhost:8000}
python.service.ask-url=${ASK_SERVICE_URL:http://localhost:8001}
python.service.internal-key=${INTERNAL_API_KEY:cheia-mea-super-secreta-123}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shared_knowledge_db}
spring.datasource.username=${DB_USERNAME:enterprise_admin}
spring.datasource.password=${DB_PASSWORD:secure_password_2026}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=univflow.app@gmail.com
spring.mail.password=${MAIL_PASSWORD:parola_dummy_pentru_build}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=250MB

spring.mail.properties.mail.debug=true